enabled: true
app:
  name: Coupons-As-Art
  description: Coupons-As-Art is a Spring Boot pet project for managing coupons

server:
  port: ${PORT:8080}
  error:
    include-message: always


# SPRING CONFIG START
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fa_coupons_ms_db_dev?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&jdbcCompliantTruncation=false&sslmode=require
    username: DEV_USER
    password: YOUR PASSWORD HERE
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      pool-name: fa_coupons_db_pool
      maximum-pool-size: 8
      connection-timeout: 20000
      max-lifetime: 30000
      idle-timeout: 10000

      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 300
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  jpa:
    database: mysql
    show-sql: true
    open-in-view: false # disable the Open Session in View anti-pattern, inefficient from a database perspective
    database-platform: org.hibernate.dialect.MySQLDialect

    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        enable_lazy_load_no_trans: true # this is inefficient as it introduces n+1 problem
        # use Hibernate Criteria API for best performance from a database perspective

  devtools:
    restart:
      enabled: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
# SPRING CONFIG END


# LOGGING CONFIG START
management:
  endpoints:
    web:
      exposure:
        include: env

logging:
  level:
    org:
      hibernate: error
# LOGGING CONFIG END